// <auto-generated />
namespace bie.evgestao.infra.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FotoParapessoa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FotoParapessoa));
        
        string IMigrationMetadata.Id
        {
            get { return "201806301521023_FotoParapessoa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
