// <auto-generated />
namespace bie.evgestao.infra.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Ajustes_pos_configPessoa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ajustes_pos_configPessoa));
        
        string IMigrationMetadata.Id
        {
            get { return "201806242010152_Ajustes_pos_configPessoa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
